# Generated by Django 2.1 on 2018-12-09 08:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[account.models.validate_username], verbose_name='ユーザー名'),
        ),
    ]
