# Generated by Django 2.1 on 2018-11-25 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'チャンネル',
                'verbose_name_plural': 'チャンネル',
            },
        ),
        migrations.CreateModel(
            name='ChannelUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='未読数')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='chat.Channel', verbose_name='チャンネル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelinfo', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'チャンネルユーザー情報',
                'verbose_name_plural': 'チャンネルユーザー情報',
            },
        ),
        migrations.CreateModel(
            name='ChatUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='未読数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatinfo', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー情報',
                'verbose_name_plural': 'ユーザー情報',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Channel', verbose_name='チャンネル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ',
            },
        ),
        migrations.AlterUniqueTogether(
            name='channeluserinfo',
            unique_together={('channel', 'user')},
        ),
    ]
