# Generated by Django 2.1 on 2018-12-02 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='未読数')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Channel', verbose_name='チャンネル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'チャンネルメンバーシップ',
                'verbose_name_plural': 'チャンネルメンバーシップ',
            },
        ),
        migrations.AlterUniqueTogether(
            name='channeluserinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='channeluserinfo',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channeluserinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChannelUserInfo',
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(through='chat.ChannelMembership', to=settings.AUTH_USER_MODEL, verbose_name='メンバー'),
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('channel', 'user')},
        ),
    ]
