# Generated by Django 2.1 on 2018-12-01 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('state', models.IntegerField(choices=[(0, '未対応'), (1, '対応中'), (2, '完了')], default=0, verbose_name='状態')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_tasks', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
            },
        ),
    ]
