# Generated by Django 2.1 on 2018-12-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='予定開始日'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='予定終了日'),
        ),
    ]
