# Generated by Django 2.1 on 2018-12-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181207_1716'),
        ('task', '0004_auto_20181207_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='番号'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'number')},
        ),
    ]
